plugins {
    id 'java'
    id 'org.springframework.boot' version '3.2.0'
    id 'io.spring.dependency-management' version '1.1.4'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

ext {
    set('springBootVersion', '3.2.0')
    set('jdaVersion', '5.2.2')
}

dependencies {
    testImplementation 'org.springframework.boot:spring-boot-starter-test'

    // Spring Boot Starter
    implementation 'org.springframework.boot:spring-boot-starter'

    // JDA Discord Bot
    implementation("net.dv8tion:JDA:$jdaVersion") {
        // Optionally disable audio natives to reduce jar size by excluding `opus-java`
        // Gradle DSL:
        // exclude module: 'opus-java'
        // Kotlin DSL:
        // exclude(module="opus-java")
    }

    // MongoDB
    implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'

    // For JDA event handling and annotations
    implementation 'org.springframework:spring-context'

    // Required for javax.annotation.PostConstruct
    implementation 'jakarta.annotation:jakarta.annotation-api:2.1.1'
}
