# Discord Bot Configuration
discord.token=${DISCORD_TOKEN:PASTE_TOKEN_HERE}

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/ianbot

# Logging
logging.level.com.ianscottbaker=DEBUG
