spring.application.name=ianbot

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=ianbot

discord.guilds.test-id=1112230651681308822
discord.guilds.fuzzy-id=270639436037881866
